### ISSUE TITLE
Export as markdown files with images to import into Obsidian and similar 

### ISSUE THREAD

**Issue by aslom** [HamburgChimps/apple-notes-liberator#19]
Set of .md files that references exported images as files in .md file:

```
# Title

text 

![[ image name .png ]]
```

That would make it very easy to to import exported .md files and images into Obsidian and other apps that use Markdown

- [ ] #24

**Comment by alexkolson** [comment]
Hello @aslom 👋 

This is a good idea! I like it! I think this should totally be added 👍

**Comment by exislow** [comment]
This idea is great and would help me a lot. I do not know, if it necessary to extract it into Obsidian or whatever directly, but it would be awesome, if you could implement an option, which extracts the Notes structure in an adequate file structure based on GitHub flavored markdown (https://docs.github.com/de/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) using textbundles (https://textbundle.org/) (important for proper asset management).

**Comment by alexkolson** [comment]
- [ ] #24

**Comment by alexkolson** [comment]
Hi @aslom and @exislow! Rudimentary markdown export functionality has been added in [`v2.0.0`](https://github.com/HamburgChimps/apple-notes-liberator/releases/tag/v2.0.0). It is in the super early stages, but would love any feedback you might have!
