### ISSUE TITLE
notesCloudObject is null

### ISSUE THREAD

**Issue by lhagan** [HamburgChimps/apple-notes-liberator#25]
I'm getting the following error when I run the jar:
```
Cannot invoke "de.hamburgchimps.apple.notes.liberator.entity.NotesCloudObject.getzTypeUti()" because "notesCloudObject" is null
```

`apple-notes-liberator` appears to have found the correct database since it copied `notes.sqlite` into the `liberated-notes` folder. I manually queried that database using the following command:
```
sqlite3 notes.sqlite "SELECT writefile('note_data.gz', zdata) FROM zicnotedata WHERE znote = 100"
```
The extracted data includes the text of one of my notes, so I don't think the problem is with the source data.

My configuration:
* macOS 13.2.1
* java "20" 2023-03-21
* apple-notes-liberator release 1.0.3

Here's some additional information from the log:
```
ERROR [de.ham.app.not.lib.dat.Table] (main) Failed to parse table: java.lang.RuntimeException: no data to parse
```
Any ideas of what might be tripping it up?

**Comment by alexkolson** [comment]
Hi @lhagan, sorry you are facing this issue! I have just released a potential fix! Could you try [v1.0.4](https://github.com/HamburgChimps/apple-notes-liberator/releases/tag/v1.0.4) and let me know if it works for you?

In case you are interested in more detailed information. The (potential) fix checks to make sure the particular notes object that the application is attempting to parse is actually not null before attempting to determine what type it is. My suspicion is that the particular notes object that the application is attempting to parse is deleted but still lingering around as an attachment in the note data itself. My general impression is that deleted note objects and references to deleted note objects can still linger around in the Notes.app database, and `apple-notes-liberator` doesn't handle such cases as well as it should. Hopefully with this change though, it should no longer attempt to determine the type of a deleted notes object and thus not throw a `NullPointerException`. I could be wrong of course, and am curious to see if v1.0.4 works for you.

Thank you for taking the time to make an issue and I hope to hear back from you!

**Comment by lhagan** [comment]
Wow -- thanks for the quick solution! v1.0.4 fixed this issue.

**Comment by alexkolson** [comment]
Awesome! Glad to hear it!
