### ISSUE TITLE
Cannot invoke "String.isEmpty()" because "typeIdentifier" is null 

### ISSUE THREAD

**Issue by cedricloneux** [HamburgChimps/apple-notes-liberator#9]
tried to run the v0.1.0 release on ARM mac and got error
`Cannot invoke "String.isEmpty()" because "typeIdentifier" is null `
 
here is the terminal history:

```
~ ₿ java -version
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment Homebrew (build 19.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 19.0.1, mixed mode, sharing)
~ ₿ java -jar ~/Downloads/apple-notes-liberator.jar 
Cannot invoke "String.isEmpty()" because "typeIdentifier" is null 
```

**Comment by alexkolson** [comment]
Hey @cedricloneux,  my bad, should have been checking for null here. Thanks @minhoryang for the fix!

Although I 'm still not convinced it will work in your case, as i'm not sure typeIdentifier should be null. Maybe give it a try and see if you get any json out?

**Comment by baibanbao** [comment]
the same problem, on my m1 mac, when running the command it says

`Cannot invoke "String.isEmpty()" because "typeIdentifier" is null `

Please debug it.

**Comment by alexkolson** [comment]
Going to close this but if @cedricloneux or anyone else has this issue with the latest release feel free to reopen this one or open a new one.
